package com.waitfans.backend;

import com.waitfans.backend.im.IMServer;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.scheduling.annotation.EnableScheduling;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@EnableScheduling   // 启用定时任务
public class WaitfansBackendApplication {

    public static void main(String[] args) {
        ConfigurableApplicationContext context =
                SpringApplication.run(WaitfansBackendApplication.class, args);
        IMServer imServer = context.getBean(IMServer.class);

        new Thread(() -> {
            try {
                imServer.start();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }, "waitfans-im-server").start();
    }

}
