package com.waitfans.backend.component.danmu.protocol;

public enum DanmuProtocolErrorCode {
    MALFORMED_FRAME,
    UNSUPPORTED_VERSION,
    UNSUPPORTED_TYPE,
    MISSING_REQUEST_ID,
    AUTH_REQUIRED,
    AUTH_EXPIRED,
    AUTH_FORBIDDEN,
    INVALID_VIDEO_ID,
    VIDEO_NOT_FOUND,
    VIDEO_NOT_PUBLIC,
    VIDEO_METADATA_INVALID,
    CONTENT_INVALID,
    STYLE_INVALID,
    TIME_POINT_INVALID,
    MESSAGE_TOO_LARGE,
    RATE_LIMITED,
    SEND_FAILED,
    SERVICE_UNAVAILABLE
}
